Arduino-CI/arduino_ci

- CHANGELOG.md
- README.md
- SampleProjects/DoSomething/.arduino-ci.yaml
- SampleProjects/DoSomething/.travis.yml
- SampleProjects/DoSomething/README.md
- SampleProjects/DoSomething/test/good-library.cpp
- SampleProjects/DoSomething/test/good-null.cpp
- SampleProjects/TestSomething/test/bad-null.cpp
- SampleProjects/TestSomething/test/good-library.cpp
- SampleProjects/TestSomething/test/good-null.cpp
- cpp/unittest/ArduinoUnitTests.h
- cpp/unittest/Assertion.h
- exe/arduino_ci_remote.rb
- lib/arduino_ci/cpp_library.rb
- misc/default.yaml
- spec/ci_config_spec.rb
* Fixes #9
* Fixes #10 
See Changelog.
> More CI fixes

- CHANGELOG.md
- CONTRIBUTING.md
- SampleProjects/TestSomething/test/queue.cpp
- SampleProjects/TestSomething/test/table.cpp
- cpp/arduino/PinHistory.h
- cpp/arduino/ci/DeviceUsingBytes.h
- cpp/arduino/ci/ObservableDataStream.h
- cpp/arduino/ci/Queue.h
- cpp/arduino/ci/Table.h
Use `ArduinoCI` prefix on the `Queue` and `Table` classes
> avoid name collisions with Queue and Table

- .github/issue_template.md
- CHANGELOG.md
- README.md
- SampleProjects/DoSomething/Gemfile.lock
- SampleProjects/TestSomething/.arduino-ci.yml
- SampleProjects/TestSomething/test/serial.cpp
- cpp/arduino/ArduinoDefines.h
- cpp/arduino/Godmode.h
- cpp/arduino/HardwareSerial.h
- cpp/arduino/Print.h
- cpp/arduino/Stream.h
- cpp/arduino/WString.h
- exe/arduino_ci_remote.rb
- lib/arduino_ci/ci_config.rb
- lib/arduino_ci/cpp_library.rb
- misc/default.yml
- spec/ci_config_spec.rb
- spec/cpp_library_spec.rb
- spec/testsomething_unittests_spec.rb
- spec/yaml/o1.yaml
* Addresses problems raised in #24 by @dfrencham
* Preprocessor detection of `g++` version and appropriate reaction for `isnan` / `isinf`
* Defines `LED_BUILTIN`
* Fixes `pgmspace` in `Print.h`
* Fixes #25
> Fix OSX compilation and other C++-related issues

- SampleProjects/DoSomething/.arduino-ci.yaml
- SampleProjects/DoSomething/Gemfile.lock
- lib/arduino_ci/arduino_downloader.rb
- lib/arduino_ci/arduino_downloader_windows.rb
- lib/arduino_ci/arduino_installation.rb
Changes:
* Updated arduino self.existing_executable function to find exe
* Added compilers to .arduino-ci.yaml so that build runs
With the updated code and g++ on the path the DoSomething example appears to run as as expected.
It is a bit clunky because the ide splash pops up all the time, can this be supressed? I guess not as the the comand line docs [here](https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc) don't seem to mention it.
> Arduino exe now found on windows

- CHANGELOG.md
- REFERENCE.md
- SampleProjects/TestSomething/test/godmode.cpp
- cpp/arduino/Arduino.h
- cpp/arduino/Godmode.cpp
- cpp/arduino/Godmode.h
- cpp/arduino/SPI.h
- exe/arduino_ci_remote.rb
- exe/ensure_arduino_installation.rb
- lib/arduino_ci/arduino_cmd.rb
- lib/arduino_ci/arduino_cmd_linux.rb
- lib/arduino_ci/arduino_cmd_linux_builder.rb
- lib/arduino_ci/arduino_cmd_osx.rb
- lib/arduino_ci/arduino_cmd_windows.rb
- lib/arduino_ci/arduino_installation.rb
- lib/arduino_ci/cpp_library.rb
- spec/arduino_cmd_spec.rb
- spec/arduino_installation_spec.rb
- spec/ci_config_spec.rb
- spec/cpp_library_spec.rb
- spec/testsomething_unittests_spec.rb
* Mock SPI
* Don't overwrite existing library directories with new downloads
* Properly pull in source files from external libraries (I think)
* Add `ensure_arduino_installation.rb` to enable testing with custom 3rd-party libraries
* Mock `attachInterrupt` and `detatchInterrupt`
* Return to the state where the OSX splash screen is hidden
* Fixes #57 
* Fixes #13 (hopefully)
* Supercedes #53
> More mocks and bugfixes

- CHANGELOG.md
- README.md
- exe/arduino_ci_remote.rb
- lib/arduino_ci/cpp_library.rb
* `libasan` is now both properly detected and explicitly reported
* Non-string values are properly `inform`ed in the build script
> Some bugfixes

- CHANGELOG.md
- CONTRIBUTING.md
- SampleProjects/TestSomething/test/stdlib.cpp
- cpp/arduino/stdlib.cpp
- cpp/arduino/stdlib.h
Provide an `itoa` function. It is present in Arduino's runtime environment but not on most (all?) host systems because itoa is not a portable standard function.
> Provide missing itoa function

- CHANGELOG.md
- REFERENCE.md
- lib/arduino_ci/arduino_downloader.rb
- lib/arduino_ci/arduino_downloader_osx.rb
- lib/arduino_ci/arduino_downloader_windows.rb
- lib/arduino_ci/arduino_installation.rb
- lib/arduino_ci/ci_config.rb
- Simplified the use of `Array.each` with a return statement; it's now simply `Array.find`
- `autolocate!` for Arduino installations now raises `ArduinoInstallationError` if `force_install` fails
- Errors due to missing YAML are now named `ConfigurationError`
- typo in documentation fixed
* Fixes #78
> Small fixes

- CHANGELOG.md
- REFERENCE.md
- exe/arduino_library_location.rb
- lib/arduino_ci/arduino_downloader.rb
- lib/arduino_ci/arduino_downloader_windows.rb
- lib/arduino_ci/arduino_installation.rb
- spec/arduino_installation_spec.rb
Adds ability to do cross-platform build scripts, ensuring that custom libraries get copied into the correct Arduino library directory.
- `ArduinoInstallation` and `ArduinoDownloader` now allow console output to optionally be set to an `IO` object of choice during `force_install`
- `ArduinoInstallation::force_install` now optionally accepts a version string
- `arduino_library_location.rb` script to print Arduino library location to stdout
* Fixes #91
> Enable redirection of installation output

- CONTRIBUTING.md
When retesting the [minimum scenario](https://github.com/ianfixes/arduino_ci/issues/69#issuecomment-457851016) today I used just
```shell
gem install bundler
```
and there were no problems like there had been earlier. So things have apparently been resolved and the version specific install workaround is no longer needed.
I tested using a separate user starting with an empty home directory, e.g. guaranteed no old stale things being picked up.
> Remove specific bundler version information, no longer needed

- CHANGELOG.md
- cpp/arduino/avr/pgmspace.h
* The `pgm_read_...` preprocessor macros in `cpp/arduino/avr/pgmspace.h` now expands to an expression with applicable type.
* Fixes #74
> Expand pgm_read_... macros

- CHANGELOG.md
- lib/arduino_ci/cpp_library.rb
> Fix vendor_bundle? behavior in CppLibrary (no longer hard-code bundle location)

- CHANGELOG.md
- CONTRIBUTING.md
- SampleProjects/TestSomething/test/null.cpp
- cpp/arduino/Arduino.h
- cpp/arduino/Nullptr.h
- cpp/unittest/Assertion.h
- cpp/unittest/Compare.h
- lib/arduino_ci/ci_config.rb
- spec/testsomething_unittests_spec.rb
- Added rspec sensitivity to the environment variable `$ARDUINO_CI_SELECT_CPP_TESTS=<glob>` (for `arduino_ci` gem hackers)
- `assertNotNull()` and `assureNotNull()` C++ comparisons
- `CiConfig::allowable_unittest_files` now uses `Pathname` to full effect
- `nullptr` now defined in its own class
- Assertions on `nullptr`
- The defintion of `nullptr`
* Fixes #102
> Fixed nullptr and made some general test speedups

- REFERENCE.md
- add hint to file `.arduino-ci.yml` related to examples
- define expected and actual on the assert functions 
* Fixes #109
> Expand Reference.md section on configuration overrides for examples

- CHANGELOG.md
- SampleProjects/TestSomething/test-something.cpp
- SampleProjects/TestSomething/test-something.h
- SampleProjects/TestSomething/test/library.cpp
- cpp/arduino/Arduino.h
- cpp/arduino/Nullptr.h
- cpp/unittest/ArduinoUnitTests.h
- cpp/unittest/Compare.h
- cpp/unittest/OstreamHelpers.h
* Homegrown `nullptr` definition removed. 
* Proper template and ostream operations added for `std::nullptr`
* Fixes #102  
* Corrects #106
* Supercedes #110
> Fix nullptr support again, remove custom implementation

- CHANGELOG.md
- SampleProjects/DoSomething/examples/AvrSleepInterrupt/.arduino-ci.yaml
- SampleProjects/DoSomething/examples/AvrSleepInterrupt/AvrSleepInterrupt.ino
- SampleProjects/DoSomething/examples/AvrWdtReset/.arduino-ci.yaml
- SampleProjects/DoSomething/examples/AvrWdtReset/AvrWdtReset.ino
- SampleProjects/TestSomething/test/adc.cpp
- SampleProjects/TestSomething/test/interrupts.cpp
- SampleProjects/TestSomething/test/isr_declaration.cpp
- SampleProjects/TestSomething/test/sleep.cpp
- SampleProjects/TestSomething/test/wdt.cpp
- cpp/arduino/Arduino.h
- cpp/arduino/AvrAdc.cpp
- cpp/arduino/AvrAdc.h
- cpp/arduino/Godmode.h
- cpp/arduino/avr/interrupt.h
- cpp/arduino/avr/sleep.h
- cpp/arduino/avr/wdt.h
This is my first pull request to contribute code to this project. Constructive feedback is therefore very welcome to allow the project to develop consistently.
- add `avr/sleep.h` with calls to `GodmodeState`
- add `avr/wdt.h` with calls to `GodmodeState`
- add new structs `SleepDef` and `WdtDef`
- add new structs in `GodmodeState` and reset them on `reset()`
- add interrupt `define` for ISR to allow the production code to specify an ISR for wdt
- rename existing `ISR` in function `attachInterrupt()` as it conflicts with AVR's `ISR`
- add storage location to allow usage of `ADCSRA`
- add tests for the new functionality
> Mock for sleep and wdt

- CHANGELOG.md
- cpp/arduino/Arduino.h
- cpp/arduino/Godmode.cpp
- cpp/arduino/Wire.h
This pull request starts the work of providing mock support for `Wire.h`. It is modelled after the previous work adding mock support for `SPI.h`. The mock functions do not do anything useful yet, but all the mocking skeleton framework should be in place, so the remaining part is "just" to implement some probes useful for unit testing. I do not have any use case for this, so I will not attempt to guess what would be useful here.
But even without any under the hood functionality, this provides great value because it allows to unit test code that uses libraries that depends on `Wire.h`.
* Begins work on #60
> Start of providing mock support for Wire.h

- REFERENCE.md
- SampleProjects/TestSomething/.arduino-ci.yml
- SampleProjects/TestSomething/excludeThis/exclude-this.cpp
- SampleProjects/TestSomething/excludeThis/exclude-this.h
- exe/arduino_ci_remote.rb
- lib/arduino_ci/ci_config.rb
- lib/arduino_ci/cpp_library.rb
- spec/testsomething_unittests_spec.rb
* Add exclude_dirs option to [unittest] section in configuration file
* Add a filter in ArduinoCI::CppLibrary to filter out the files in directories specified there
* Adjust unittests to take the new feature into account
* Fixes #29
> include ability to exclude certain directories from compilation

- CHANGELOG.md
- REFERENCE.md
- SampleProjects/TestSomething/.arduino-ci.yml
- SampleProjects/TestSomething/excludeThis/exclude-this.cpp
- SampleProjects/TestSomething/excludeThis/exclude-this.h
- arduino_ci.gemspec
- exe/arduino_ci_remote.rb
- lib/arduino_ci/ci_config.rb
- lib/arduino_ci/cpp_library.rb
- spec/ci_config_spec.rb
- spec/cpp_library_spec.rb
- spec/testsomething_unittests_spec.rb
* Resolves review comments in #126
* Fixes #29
* Unit testing configuration now allows `exclude_dirs` to be set, which prevents stray source files from as part of unit testing allows
> Add support to exclude directories

- .rubocop.yml
Running a `bundle install` locally in one of the sample projects can leave behind a vendor bundle that the top-level Rubocop will try to inspect.
This explicitly ignores those.
* Fixes #152
> Explicitly exclude sample projects from Rubocop tests

- CHANGELOG.md
- README.md
- SampleProjects/DoSomething/library.properties
- SampleProjects/TestSomething/library.properties
- arduino_ci.gemspec
- lib/arduino_ci/cpp_library.rb
> Move repo to Arduino-CI GitHub Org

- CHANGELOG.md
- cpp/unittest/OstreamHelpers.h
Possible fix for #170. I'm not sure when Xcode started providing this, but it feels recent and this change allows tests to pass for me on my local build. I've tried to make it safe for everyone else.
> Don't define ostream& operator() if already defined by Apple

- README.md
- SampleProjects/DoSomething/test/README.md
- SampleProjects/README.md
This should avoid the impression that they are templates to be followed too closely. This is a partial fix for #149.
> Update docs to explain purpose of SampleProjects

- README.md
- SampleProjects/DoSomething/test/README.md
- SampleProjects/README.md
I believe that the changes to `ttd` are ready to merge but it would be easier to see the diffs if `tdd` were current.
> Merge `master` into `ttd` to reduce diffs

- README.md
- SampleProjects/DoSomething/test/README.md
- SampleProjects/README.md
- SampleProjects/TestSomething/test/eeprom.cpp
- cpp/arduino/Godmode.h
> Add tests for EEPROM

- CHANGELOG.md
- lib/arduino_ci/cpp_library.rb
This seems to be expected by some headers; see [Sd2PinMap.h](https://github.com/arduino-libraries/SD/blob/master/src/utility/Sd2PinMap.h):47.
> Add `__AVR__` to defines to match Arduino IDE compiler 

- REFERENCE.md
> Add documentation for EEPROM

- CHANGELOG.md
- cpp/arduino/AvrMath.h
This takes the edits from [here](https://github.com/matthijskooijman/arduino_ci/commit/e356ad78f36720d66ff46551d444f1a3687a484b) and makes them a separate PR.
Fixes #133 (and #165), simplifies #189, and replaces part of #144.
> Prevent name clashes with math macros

- CHANGELOG.md
- SampleProjects/TestSomething/test/outputRegister.cpp
- cpp/arduino/Godmode.h
I don't understand this very well, but it appears that some boards use memory-mapped I/O to read/write pins. To support that style of code this PR adds an array that can hold pin values. A more elaborate approach would be to connect to the pin logs, but this seems like a decent first step (and allows some files to compile that didn't compile before). Fixes #193.
> Provide digitalPinToPort and related functions

- SampleProjects/TestSomething/test/eeprom.cpp
- cpp/arduino/EEPROM.h
- cpp/arduino/Godmode.cpp
- cpp/arduino/Godmode.h
> Rewrite EEPROM.h to avoid GNU-licensed code

- SampleProjects/NetworkLib/test/test.cpp
Use new `arduino_ci.rb` and `--skip-examples-compilation` now that they are available.
> Update test comment to replace deprecated scripts

- CHANGELOG.md
- lib/arduino_ci/cpp_library.rb
See https://github.com/jgfoster/Adafruit_MAX31865/runs/1401861281?check_suite_focus=true for a failure.
> Fix typo in `aux_libraries` name

- CHANGELOG.md
- SampleProjects/TestSomething/test/outputRegister.cpp
- cpp/arduino/Godmode.h
Fix #210 (follow-up from #193).
> Add macro for `portInputRegister()`

- .gitattributes
In setting up GitHub Actions, I noticed that `bundle exec rubocop -D .` was throwing 25 offense for something like this:
```
Gemfile:1:1: C: Layout/EndOfLine: Carriage return character detected.
source "https://rubygems.org" ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I added a `.gitattributes` file to force **lf** line endings to match the rubocop settings in `.rubocop.yml`
> Add git attributes to force only lf line endings

- .github/workflows/macos.yaml
Highlights how the latest macOS currently does NOT run Arduino CI. Related to issues #155 and #185.
> Actions macos

- CHANGELOG.md
- lib/arduino_ci/arduino_installation.rb
- spec/arduino_installation_spec.rb
> expose DESIRED_ARDUINO_CLI_VERSION

- .github/workflows/linux.yaml
- .github/workflows/macos.yaml
- .github/workflows/windows.yaml
- .rubocop.yml
- CHANGELOG.md
- Gemfile
- REFERENCE.md
- exe/arduino_ci.rb
- exe/arduino_ci_remote.rb
- exe/ensure_arduino_installation.rb
- lib/arduino_ci/arduino_backend.rb
- lib/arduino_ci/arduino_downloader.rb
- lib/arduino_ci/ci_config.rb
- lib/arduino_ci/cpp_library.rb
- lib/arduino_ci/host.rb
- spec/arduino_ci_spec.rb
- spec/cpp_library_spec.rb
- spec/host_spec.rb
- `ensure_arduino_installation.rb` now ensures the existence of the library directory as well
- Environment variables to escalate unit tests or examples not being found during CI testing
- Conserve CI testing minutes by grouping CI into fewer runs
- Improper reference to `Host` in `arduino_ci.rb` test runner is now properly qualified
- Failure to set board manager URLs (for 3rd party board providers) has been fixed
* Fixes #230 
* Fixes #231
* Fixes #233
> Fixes for GitHub Action

- .github/workflows/README.md
- .rubocop.yml
- CHANGELOG.md
- REFERENCE.md
- SampleProjects/TestSomething/test/godmode.cpp
- cpp/arduino/Arduino.h
- cpp/arduino/ArduinoDefines.h
- cpp/arduino/Godmode.h
- cpp/unittest/Assertion.h
- exe/arduino_ci.rb
- lib/arduino_ci/arduino_backend.rb
- lib/arduino_ci/ci_config.rb
- lib/arduino_ci/library_properties.rb
- misc/default.yml
- spec/arduino_backend_spec.rb
- spec/ci_config_spec.rb
- spec/library_properties_spec.rb
- `esp8266:huzzah` options updated as per upstream
* Fixes #254 - Huzzah / invalid option FlashSize
* Fixes #252 - `shiftIn` support
* Fixes #249 - `pinMode` and `_NOP`
* Fixes #246 - respect `architecture=` when iterating
* Fixes #258 - remove overzealous `pinMode` macro
* Fixes #237  - scan `library.properties` for typos
* Fixes #261 - add information about platform names being case sensitive
* Fixes #262 - scan `library.properties` for typos
> Finish 2020 milestone

- .github/workflows/linux.yaml
- .github/workflows/macos.yaml
- .github/workflows/windows.yaml
- CHANGELOG.md
- README.md
- REFERENCE.md
- SampleProjects/README.md
- SampleProjects/TestSomething/README.md
- exe/arduino_ci.rb
- Better indications of the build phases in the test runner `arduino_ci.rb`
- Better indications of which example sketch is being compiled as part of testing
- Topmost installtion instructions now suggest `gem install arduino_ci` instead of using a `Gemfile`.  Reasons for using a `Gemfile` are listed and discussed separately further down the README.
- scanning of `library.properties`; this can and should now be performed by the standalone [`arduino-lint` tool](https://arduino.github.io/arduino-lint).
- Example sketches with no configured platforms were printing the wrong configuration values to the debug message
- Libraries directory was not being automatically created prior to attempting to change directory into it
- A style error whose "fix" caused an _actual_ error.
* Fixes #264 - …
> Beta test branch for next release

- CHANGELOG.md
- exe/arduino_ci.rb
- lib/arduino_ci/arduino_backend.rb
> Test for minimum free memory

- CHANGELOG.md
- SampleProjects/TestSomething/test/stream.cpp
- cpp/arduino/Stream.h
The delimiter should not be included in the returned String.
> Stream::readStreamUntil() should not return delimiter

- CHANGELOG.md
- cpp/arduino/Arduino.h
Replace `#define yield() _NOP()` with `inline void yield() { _NOP(); }` so that other code can define a `yield()` function.
> Allow `yield()` to be defined in library code

- CHANGELOG.md
- cpp/arduino/Arduino.h
Referenced 4121 times in 229 files but never defined!?
> Add `_BV()` macro definition

- CHANGELOG.md
- SampleProjects/TestSomething/test/clientServer.cpp
- cpp/arduino/Client.h
if you have a custom destructor, then you probably need a custom copy constructor and a custom copy assignment operator.
> Rule of three for Client

- CHANGELOG.md
- SampleProjects/TestSomething/test/wdt.cpp
- cpp/arduino/avr/wdt.h
Add `avr/wdt.h` and simple test that ensures the header can be found and the functions can be called.
> Allow compiling with Watchdog Timer calls

- CHANGELOG.md
- SampleProjects/TestSomething/test/stdlib.cpp
- cpp/arduino/stdlib.cpp
- cpp/arduino/stdlib.h
Replacement for prior commit. This one is a branch from master instead of main.
> Add support for dtostrf()

- lib/arduino_ci/arduino_downloader.rb
This fixes the [issue](https://github.com/Arduino-CI/arduino_ci/issues/291) where attempting to download releases from <https://github.com/arduino/arduino-cli/releases/download/> fails.
> Fix open-uri call for downloading release files

- .gitattributes
- .github/workflows/linux.yaml
- .github/workflows/macos.yaml
- .github/workflows/spelling.yaml
- .github/workflows/windows.yaml
- CHANGELOG.md
- CONTRIBUTING.md
- Gemfile
- README.md
- SampleProjects/TestSomething/Gemfile
- exe/arduino_ci.rb
- lib/arduino_ci/arduino_backend.rb
- lib/arduino_ci/arduino_downloader.rb
- lib/arduino_ci/arduino_downloader_linux.rb
- lib/arduino_ci/arduino_downloader_osx.rb
- lib/arduino_ci/arduino_downloader_windows.rb
- lib/arduino_ci/arduino_installation.rb
- lib/arduino_ci/cpp_library.rb
- lib/arduino_ci/host.rb
- lib/arduino_ci/library_properties.rb
- misc/default.yml
- spec/arduino_backend_spec.rb
- spec/arduino_downloader_spec.rb
- spec/arduino_installation_spec.rb
- spec/ci_config_spec.rb
- spec/cpp_library_spec.rb
- spec/fake_lib_dir.rb
- spec/host_spec.rb
- spec/testsomething_unittests_spec.rb
Getting a lot of old stuff merged in
* Fixes #327 more properly
* Fixes #335 
* Fixes #277
* Replaces #323
* Replaces #330 - good catch @hlovdal 
* Fixes #324
* Fixes #315
* Replaces #287 - thanks @midasgossye 
* Supersedes #296
* Fixes #295
* Fixes #283
* Supersedes #285 
* Fixes #282
* Supersedes #297
* Fixes #288
* Supersedes #289
* Supersedes #298 
* Supersedes #286 
* Fixes #269
* Supersedes #290
* Addresses #280
TODO:
* Could not merge https://github.com/Arduino-CI/arduino_ci/pull/296/commits/1ee342c18740e665b265cc81af346c9ee160c208
> Work in progress: 2022 Mergefest

- CHANGELOG.md
- cpp/arduino/ArduinoDefines.h
Updates to CHANGELOG.md will trigger conflicts for this branch (`led_builtin.m`, rebased on top of `master`) when #338 is completed (or if this is done first, then #338 will get conflicts).
There is an alternative branch `led_builtin` applied in series with other branches that does not have those conflicts when #338 is completed. Let me know if you rather want that one merged (later).
> Make LED_BUILTIN definition available for Arduino Due, Zero and Circuit Playground

- .github/workflows/linter.yaml
- .github/workflows/linux.yaml
- .github/workflows/macos.yaml
- .github/workflows/spelling.yaml
- .github/workflows/windows.yaml
- CHANGELOG.md
- README.md
- REFERENCE.md
- SampleProjects/TestSomething/examples/.arduino-ci.yml
- SampleProjects/TestSomething/examples/TestSomethingExample/.arduino-ci.yml
- cpp/arduino/Arduino.h
- cpp/arduino/ArduinoDefines.h
- cpp/arduino/Godmode.h
- exe/arduino_ci.rb
- lib/arduino_ci/arduino_backend.rb
- lib/arduino_ci/ci_config.rb
- lib/arduino_ci/host.rb
- spec/ci_config_spec.rb
- spec/host_spec.rb
This cleans up the `v1.4.0` release and makes progress on past milestones
* Fixes #159
* Fixes #339
* Fixes #336 
* Fixes #273
* Fixes #272
> Further bugfixes and documentation fixes

- CHANGELOG.md
- exe/arduino_ci.rb
Free space should be greater than or equal to the desired minimum.
> Fix size check message

- CHANGELOG.md
- SampleProjects/TestSomething/test/atomic.cpp
- cpp/arduino/util/atomic.h
Hi,
I had the problem that I wanted to check a library modified by me which in turn includes a library that includes util/atomic.h and that doesn't work, of course. I added a mocked version of util/atomic.h, that simply does nothing. Atomicity by switching off interrupts is not possible on the host OS but timing behavior will differ anyway, therefore I think this approach is acceptable.
Best,
Gunter
> Add util/atomic.h 

- CHANGELOG.md
- cpp/arduino/ArduinoDefines.h
- cpp/arduino/avr/interrupt.h
- exe/arduino_ci.rb
- lib/arduino_ci.rb
- lib/arduino_ci/logger.rb
* Using new logging class to remove arbitrary whitespace placement in favor of explicit functionality for adjusting indentation levels.
* #321 
* Fixes #14
> Logging improvements

- .github/workflows/linux.yaml
- CHANGELOG.md
- SampleProjects/BusIO/.arduino-ci.yml
- SampleProjects/BusIO/README.md
- SampleProjects/BusIO/library.properties
- exe/arduino_ci.rb
> Fix issue #352 - backend used before assigned when loading dependencies
